### ISSUE TITLE
UML_Uebungsblatt1_Aufgabe_4

### ISSUE THREAD

**Issue by ngaeng** [sweIhm-ws2018-19/skillproject-fr-14#1]

**Comment by ngaeng** [comment]
[UML_Uebungsblatt1_Aufgabe4.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/files/2495280/UML_Uebungsblatt1_Aufgabe4.zip)

**Comment by kkaiser12** [comment]
[uml_reviewed.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/files/2495581/uml_reviewed.zip)

Geldbetrag ist laut dem UML-Diagramm eine eigene Klasse und kein int.
Deswegen wurde eine zusätzliche Klasse erstellt und in der Klasse Konto mit Gettern
und Settern auf den Betrag zugegriffen.

**Comment by Chrysotomus** [comment]
Ich bin die Files der Aufgabe 4 inzwischen durchgegangen. In den Dateien "Geschaeftskunde", "Kunde" und "Privatkunde" habe ich euch in Form von Kommentaren am Ende des Java Quelltextes Verbesserungsvorschläge hinterlassen. 
[UML_Uebungsblatt1_Aufgabe4.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/files/2498066/UML_Uebungsblatt1_Aufgabe4.zip)

**Comment by ngaeng** [comment]
Vielen Dank für Euer Feedback! 
Ich habe nochmal in der Klasse Konto den Parameter der Methode einzahlen vom Typ int auf Geldbetrag geändert.
Falls niemand mehr etwas ändern/vorschlagen möchte werde ich den Issue schließen.

[UML_Uebungsblatt1_Aufgabe4_final.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/files/2498135/UML_Uebungsblatt1_Aufgabe4_final.zip)
