### ISSUE TITLE
Übungsblatt 2: Aufgabe 4

### ISSUE THREAD

**Issue by ngaeng** [sweIhm-ws2018-19/skillproject-fr-14#10]
![aufgabe4](https://user-images.githubusercontent.com/43876351/47580340-f8399580-d94e-11e8-9b42-8e81f7cf6776.jpg)

**Comment by ngaeng** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-14/tree/master/UML/Uebungsblatt2/Aufgabe_4

**Comment by ngaeng** [comment]
Ich bin mir sehr unsicher was die Aufgabe angeht, habe aber keine bessere umsetzbare Lösung als das ^ gefunden. Problem dabei könnte sein, dass die Blende vor dem Blitz geschlossen wird, falls diese Aktion aus irgendeinem Grund deutlich weniger Zeit braucht als der Blitz. Ich hatte überlegt nach Blitz zünden & Blende öffnen die Stränge zu synchronisieren bevor die Blende geschlossen wird, aber zumindest ist mir keine Möglichkeit eingefallen bei der das ganze Konstrukt anschließend noch funktioniert.

**Comment by kkaiser12** [comment]
Also ich finde es so eigentlich logisch aufgebaut. Wegen dem synchronisieren fällt mir auch keine bessere Lösung ein, weil wenn man die Pfeile zusammenführt, weiß man ja nachher nicht mehr, ob man jetzt den Blitz zünden muss oder nicht.
