### ISSUE TITLE
Übungsblatt 2: Aufgabe 7

### ISSUE THREAD

**Issue by Chrysotomus** [sweIhm-ws2018-19/skillproject-fr-14#11]
![aufgabenblatt2_aufgabe7](https://user-images.githubusercontent.com/7889490/47617124-6eabd400-dac4-11e8-92b7-fc358ac65082.jpg)

Ich denke zwar, dass das so passen müsste. Wäre allerdings super, wenn da nochmal jemand einen Blick drüber werfen kann. Danke im Voraus!

**Comment by kkaiser12** [comment]
Ich würde sagen, dass es von der Logik so passt, bin mir aber wegen den Pfeilen nicht sicher. Ich hab in den Folien gefunden, dass man die gestrichelten Pfeile für Interfaces benutzt. Hier soll der Pfeil ja aussagen, dass die Klasse, von der der Pfeil ausgeht, ein Objekt von der anderen Klasse als Attribut benutzt, oder? (Das braucht sie ja um die Methode aufzurufen.) 
Müsste das dann nicht eher ein Pfeil mit einer normalen Linie sein?

**Comment by Chrysotomus** [comment]
Ich hatte es ursprünglich mit normaler Linie, habe mir von einem Kommilitonen allerdings sagen lassen, dass die gestrichelten Linien Abhängigkeiten von Klassen aufzeigen. In diesem Fall heißt das, dass Klasse B unabhängig von Klasse A ist. Klasse A braucht allerdings Klasse B. Das Selbe gilt für C und D. Diese brauchen beide B nicht, aber B braucht diese beiden. Auf dieser Argumentation sind diese Pfeile begründet. Ich bin mir allerdings auch nicht sicher, ob die durchgezogenen Linien es nicht auch getan hätten
