### ISSUE TITLE
Übungsblatt 2: Aufgabe 9

### ISSUE THREAD

**Issue by Chrysotomus** [sweIhm-ws2018-19/skillproject-fr-14#12]
![aufgabenblatt2_aufgabe9](https://user-images.githubusercontent.com/7889490/47617138-a0249f80-dac4-11e8-8d2e-77a810917b3e.jpg)

Bitte nochmal einen genauen Blick auf diese Lösung werfen. Ich bin mir nicht sicher, ob das so richtig gelöst ist. Ich denke, dass die Reihenfolge der Druckprozesse zwar irrelevant ist, das dürfte also passen.

**Comment by Chrysotomus** [comment]
Sollen vielleicht die Namen der Objekte so geändert werden, dass sie zu denen im Objektdiagramm passen? Dann sieht das Layout in manchen Kästen nunmal sehr komisch aus.

**Comment by ngaeng** [comment]
Das sollte so passen denke ich, Reihenfolge auf jeden Fall auch. Das mit dem Umbenennen ist hoffentlich nicht so wichtig, es ist definitiv klar erkennbar was gemeint ist.

**Comment by sfrank13** [comment]
Ich finde das auch sehr übersichtlich und die Benennungen sind auch klar definiert.
