### ISSUE TITLE
Begrüßung

### ISSUE THREAD

**Issue by kkaiser12** [sweIhm-ws2018-19/skillproject-fr-14#14]
**User-Story: Begrüßung**
Als Nutzer will ich wissen, welche Funktionen ich innerhalb des Skills aufrufen kann. Der Skill soll mir die Optionen aufzählen. 

**Akzeptanzkriterien**
- Begrüßung vorhanden
- mögliche Funktionen werden aufgezählt (Liste ausgeben, neue Fach-Gegenstandszuordnung)

**Comment by ngaeng** [comment]
Das ist das help, oder?

**Comment by kkaiser12** [comment]
Nein, das ist die Begrüßung ganz am Anfang, Da muss man ja erstmal festlegen, ob man etwas zur Liste hinzufügt oder ob man sie abrufen will.

**Comment by kkaiser12** [comment]
Name | Begrüßung (UC 2)
-- | --
Kurzbeschreibung |  Der Skill begrüßt den User. Falls der User noch keine Gegenstandszuordnungen hinterlegt hat, wird er darauf hingewiesen, dass dies möglich ist. 
Akteure | User
Auslöser |  Der User sagt "Alexa, starte Tasche packen"
Vorbedingungen |  keine
Eingehende 		Informationen |   keine
Ergebnis(se) | keine  
Nachbedingungen |  keine
Ablauf |  Der User sagt "Alexa, öffne Tasche packen". Der Skill begrüßt ihn mit "Willkommen bei Tasche packen" oder ähnlichem.  Falls die Liste leer ist, sagt Alexa "Wenn du einen Gegenstand hinzügen willst, sage 'Gegenstand hinzufügen'"
Offene Punkte |  Man könnte evtl. den User mit Namen begrüßen. Außerdem könnte man die Begrüßung abhängig von der Tageszeit variieren (z.B "Guten Morgen")
Änderungshistorie |  Kristina Kaiser 11.11.2018
Sonstiges, 			Anmerkungen |  /

**Comment by Chrysotomus** [comment]
Ich würde vorschlagen, dass Alexa bei der Begrüßung nur daran erinnert, dass man eine neue Fach-Gegenstandszuordnung machen kann, wenn die Gegenstandsliste aktuell leer ist. Ansonsten gehört das Erinnern an Funktionen meiner Meinung nach eher zu dem Skill 'Help'

**Comment by kkaiser12** [comment]
Ok, passt, dann ändere ich das in der User Story und der Anwendungsfallbeschreibung.

**Comment by ngaeng** [comment]
**Review**
Ich denke das sieht alles sehr gut aus. Ich finde das mit den booleans eine gute Lösungsmöglichkeit auf die anderen Handler reagieren zu können. 
Der Code sieht soweit gut aus und funktioniert auch im AWS und der Konsole.
