### ISSUE TITLE
Einpackliste Uni

### ISSUE THREAD

**Issue by kkaiser12** [sweIhm-ws2018-19/skillproject-fr-14#15]
**User Story: Einpackliste Uni**
Als User will ich wissen, was ich heute für die Uni  in meine Tasche packen soll.  Dabei soll der Fall berücksichtigt werden, dass ich ein Fach an diesem Tag nicht besuchen werde. 

**Akzeptanzkriterien**
- Zuordnung stimmt
- Weglassen von einzelnen Fächern möglich

**Comment by sfrank13** [comment]
Name | Einpackliste Uni (UC 3)
-- | --
Kurzbeschreibung | Alexa sagt dem Benutzer, welche 			Dinge er in seine Tasche für die Uni einpacken soll. Jedoch 			erzählt das Alexa nur für den Tag an dem der User den neuen 			Alexa Skill aufruft.
Akteure | User
Auslöser | Aufruf des Alexa Skills „Tasche 			packen“
Vorbedingungen | UC 1 vorhanden
Eingehende Informationen | Fächer, benötigte Utensilien, 			ZPA Stundenplan
Ergebnis(se) | Einpackliste für den Tag des 			Aufrufs
Nachbedingungen | ---
Ablauf | **1.Abfrage des Datums des 	Aufrufs:** <br>Der Alexa Skill ruft das Datum 	auf und speichert es intern ab, damit man im späteren Verlauf darauf zugreifen kann. ZPA Stundenplan abfragen:  Der Alexa Skill ruft im Hintergrund, durch einen Schnittstelle im System des ZPAs, den Stundenplan auf.<br> **2. Verknüpfung des Wochentags mit dem ZPA Stundenplan:** 	<br>	Durch das genaue Datum weiß der 			Alexa Skill, welcher Wochentag ist. Somit kann Alexa die Einpackliste für den jetzigen Wochentag zusammenstellen und die Fächer auswählen Utensilien zusammenstellen: 			Nachdem Alexa die Fächer weiß, kann sie auf die davor gespeicherten Informationen zugreifen. 	Somit stellt Alexa alle benötigten Utensilien zusammen. Dies hat zur Folge, dass Alexa die Utensilien nacheinander aufzählt.
Offene Punkte | ---
Änderungshistorie | Datum, 			Fach, 			Utensil(ien)
Sonstiges, Anmerkungen | Es ist schon eine Default 			Einpackliste vorhanden

**Comment by sfrank13** [comment]
Hier bitte auch überprüfen ob alles stimmt. 
Leider Funktioniert die Formatierung bei dem Unterpunkt "Ablauf" nicht so gut. Somit stehen leider die Zahlen nicht untereinander.

**Comment by kkaiser12** [comment]
Ich hätte eher nicht gedacht, dass in die Anwendungsfallbeschreibung  technische Details, wie z.B. die ZPA-Abfrage reinkommen, bin mir aber auch nicht sicher. Weiß das zufällig jemand?

**Comment by sfrank13** [comment]
Name | Einpackliste Uni (UC 3)
-- | --
Kurzbeschreibung | Alexa sagt dem Benutzer, welche 			Dinge er in seine Tasche für die Uni einpacken soll. Jedoch 			erzählt das Alexa nur für den Tag an dem der User den neuen 			Alexa Skill aufruft.
Akteure | User
Auslöser | Aufruf des Alexa Skills „Tasche 			packen“
Vorbedingungen | UC 1 vorhanden
Eingehende Informationen | Fächer, benötigte Utensilien, 			ZPA Stundenplan
Ergebnis(se) | Einpackliste für den Tag des 			Aufrufs
Nachbedingungen | ---
Ablauf | 1. Abfrage von dem Datum des 			Aufrufs <br>			Der Alexa Skill ruft das Datum 			auf und speichert es intern ab, damit man im späteren Verlauf 			darauf zugreifen kann. 			2. ZPA Stundenplan abfragen <br>			Der Alexa Skill ruft im 			Hintergrund, durch einen Schnittstelle im System des ZPAs, den 			Stundenplan auf. 			3. Verknüpfung von dem 			Wochentag mit dem ZPA Stundenplan<br>  			 			Durch das genaue Datum weiß der 			Alexa Skill, welcher Wochentag ist. Somit kann Alexa die 			Einpackliste für den jetzigen Wochentag zusammenstellen und die 			Fächer auswählen 			4. Utensilien zusammenstellen<br>			 			Nachdem Alexa die Fächer weiß, 			kann sie auf die davor gespeicherten Informationen zugreifen. 			Somit stellt Alexa alle benötigten Utensilien zusammen. Dies hat 			zur Folge, dass Alexa die Utensilien nacheinander Aufzählt.
Offene Punkte | ---
Änderungshistorie | geändert am 09.11.2018 von Sara 			Frank
Sonstiges, Anmerkungen | Es ist schon eine Default 			Einpackliste vorhanden

**Comment by sfrank13** [comment]
Name | Einpackliste Uni (UC 3)
-- | --
Kurzbeschreibung | Alexa sagt dem Benutzer, welche 			Dinge er in seine Tasche für die Uni einpacken soll. Jedoch 			erzählt das Alexa nur für den Tag an dem der User den neuen 			Alexa Skill aufruft.
Akteure | User
Auslöser | Aufruf des Alexa Skills „Tasche 			packen“
Vorbedingungen | UC 1 vorhanden
Eingehende Informationen | Fächer, benötigte Utensilien, 			ZPA Stundenplan
Ergebnis(se) | Einpackliste für den Tag des 			Aufrufs
Nachbedingungen | ---
Ablauf | 1. Abfrage von dem Datum des 			Aufrufs <br>			Der Alexa Skill ruft das Datum 			auf und speichert es intern ab, damit man im späteren Verlauf 			darauf zugreifen kann. 	<br>		2. ZPA Stundenplan abfragen<br>			Der Alexa Skill ruft im 			Hintergrund, durch einen Schnittstelle im System des ZPAs, den 			Stundenplan auf. 	<br>		3. Verknüpfung von dem 			Wochentag mit dem ZPA Stundenplan<br>  			 			Durch das genaue Datum weiß der 			Alexa Skill, welcher Wochentag ist. Somit kann Alexa die 			Einpackliste für den jetzigen Wochentag zusammenstellen und die 			Fächer auswählen 		<br>	4. Utensilien zusammenstellen<br>  			 			Nachdem Alexa die Fächer weiß, 			kann sie auf die davor gespeicherten Informationen zugreifen. 			Somit stellt Alexa alle benötigten Utensilien zusammen. Dies hat 			zur Folge, dass Alexa die Utensilien nacheinander Aufzählt.
Offene Punkte | ---
Änderungshistorie | geändert am 09.11.2018 von Sara 			Frank
Sonstiges, Anmerkungen | Es ist schon eine Default 			Einpackliste vorhanden

**Comment by kkaiser12** [comment]
[](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/blob/develop/klassendiagramm_faecherausgabe.PNG)
