### ISSUE TITLE
Einpackliste Wetter

### ISSUE THREAD

**Issue by kkaiser12** [sweIhm-ws2018-19/skillproject-fr-14#16]
**User Story: Einpackliste Wetter**
Als User möchte ich wissen, was ich aufgrund des Wetters zusätzlich einpacken soll, wie z.B. einen Regenschirm. Der Skill soll mir hierzu Vorschläge machen. 

**Akzeptanzkriterien**
- Vorschläge sollen zu Wetter passen

**Comment by sfrank13** [comment]
Name | Einpackliste Wetter (UC 4)
-- | --
Kurzbeschreibung | Damit der Nutzer nicht 			aufgeschmissen ist, wenn das Wetter nicht so mitspielt wie er 			möchte, gibt Alexa zum Schluss noch einen kleinen Tipp über das 			Wetter. Somit kann der Benutzer sich darauf einstellen und Alexa 			kann optional noch einen Gegenstand zu der Einpackliste 			hinzufügen.
Akteure | User
Auslöser | Einpackliste Uni (UC 3) beendet
Vorbedingungen | Fest abgespeichert, welcher Tipp 			bei einem bestimmten Wetter aufgerufen werden soll.
Eingehende Informationen | Wetterdaten
Ergebnis(se) | Wetterergebnisse + Tipp
Nachbedingungen | ---
Ablauf | **1. Wetterdaten abfragen** <br> 			Der Alexa Skill holt sich die 			Wetterdaten nur von dem Tag des Aufrufs und speichert diese 			separat ab. 		<br>	**2. Wetterdaten vergleichen** 		<br>	Die vorliegenden Wetterdaten 			werden mit den zuvor gespeicherten Tipps der einzelnen 			Wettersituationen verglichen. 	<br>		 **3. Ausgabe des Tipps** 		<br>	Beispielsweise wird der Alexa 			Skill dem User bei regnerischem Wetter den Tipp geben, dass 			dieser einen Regenschirm in seine Tasche packen sollte.
Offene Punkte | Kleidungstipp evtl. noch 			einbauen
Änderungshistorie | Datum, Tipp zuvor, Tipp jetzt
Sonstiges, Anmerkungen | ---

**Comment by sfrank13** [comment]
Bitte schauen, ob das so stimmt. 
Bei dem Ablauf sollte die Nummerierung untereinander stehen, leider Funktioniert das hier nicht so gut.

**Comment by kkaiser12** [comment]
Du kannst in die nächste Zeile mit  "br" in spitzen Klammern springen. Ich kann es hier nicht ausschreiben, weil es nicht angezeigt wird, sondern nur einen Zeilenumbruch gibt. :)

**Comment by ngaeng** [comment]
Ich denke das werden wir aufgrund von Zeitmangel nicht mehr umsetzen
