### ISSUE TITLE
Verabschiedung

### ISSUE THREAD

**Issue by kkaiser12** [sweIhm-ws2018-19/skillproject-fr-14#18]
**User Story: Verabschiedung**
Als Nutzer möchte ich, dass Alexa sich von mir verabschiedet. 

**Akzeptanzkriterien**
- Alexa verabschiedet sich mit unterschiedlichen Wendungen.

**Comment by kkaiser12** [comment]
Name | Verabschiedung (UC 5)
-- | --
Kurzbeschreibung |  Der Skill verabschiedet sich vom User mit unterschiedlichen Wendungen. 
Akteure | User
Auslöser |  Alle anderen Anwendungsfälle wurden beendet. 
Vorbedingungen |  keine
Eingehende Informationen |  keine
Ergebnis(se) |  Der Skill verabschiedet sich.
Nachbedingungen |  keine
Ablauf |  Der Skill sagt einen Abschiedssatz. 
Offene Punkte |  Evtl. könnte man die vorher verwendeten Daten verwenden, um die Verabschiedung an die Situation anzupassen, z.B. "Viel Spaß heute bei SoftwareEngineering."
Änderungshistorie |  geändert am 10.11.2018 von Kristina Kaiser
Sonstiges, 			Anmerkungen |  Der Skill soll sich nicht immer mit dem gleichen Satz verabschieden, sondern aus einer Liste von Sätzen einen auswählen.

**Comment by ngaeng** [comment]
**Review**
Funktioniert an sich gut, auch mit der zufälligen Generierung, im nächsten Sprint sollten wir noch schauen, dass der Handler den Aufruf terminiert, damit man danach nicht mehr stop aufrufen muss.

**Comment by ngaeng** [comment]
sollte jetzt terminieren
