### ISSUE TITLE
Übungsblatt 1 Aufgabe 5 - Objectdiagram

### ISSUE THREAD

**Issue by Chrysotomus** [sweIhm-ws2018-19/skillproject-fr-14#2]
Kristina und ich haben uns der Aufgabe 5 des ersten Übungsblattes gestellt. Es wäre gut, wenn die restlichen Teammitglieder einen Blick drüber werfen könnten. 

[Objectdiagram.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/files/2495491/Objectdiagram.zip)

**Comment by ngaeng** [comment]
Reviewer: Sara Frank & Nina Gäng

**Comment by ngaeng** [comment]
Eure Lösung wirkt auf mich sehr schlüssig. Ich habe lediglich bei der Adresse jeweils die Postleitzahl in Anführungszeichen gesetzt, da sie im Klassendiagramm von Aufgabe 4 als String vermerkt ist.

[Objectdiagram.zip](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/files/2498120/Objectdiagram.zip)

**Comment by Chrysotomus** [comment]
Hervorragend. Danke. Damit schließe ich dieses 'Issue'
