### ISSUE TITLE
Storyline

### ISSUE THREAD

**Issue by ngaeng** [sweIhm-ws2018-19/skillproject-fr-14#21]

**Comment by ngaeng** [comment]
Ein paar Fragen sind für mich noch offen geblieben:
(1) Alexa sollte ja eigentlich Daten gespeichert sagen, nachdem der User Fächer hinzugefügt hat. Problem dabei ist, dass man das an den Anfang des darauffolgenden Blocks packen müsste - das ist aber der Willkommensblock, eine Möglichkeit nicht bei der ersten Alexa-Ausgabe zu beginnen habe ich nicht gefunden. 
(2) Brauche ich ein else bei einfachen ja/nein Fragen? Oder sagt Alexa automatisch "ich habe Dich nicht verstanden, wenn sie mit einer Eingabe nichts anfangen kann?
(3) Bei den Wetterdaten weiß ich nicht ob wir den User überhaupt fragen wollen, ob er sie braucht. Falls nicht ist es schwierig das in dem Tool zu organisieren

**Comment by ngaeng** [comment]
**Link zum Projekt**
https://getstoryline.com/shared/projects/4f6f711f2245150756c55b2bf999190f57c315d8

**Comment by ngaeng** [comment]
Punkt (1) hat sich erübrigt

**Comment by ngaeng** [comment]
Es wäre gut wenn ihr testen könntet ob bei euch das abspielen funktioniert. Ich scheitere immer an der ersten Eingabe aber ich denke fast, dass das an irgendwelchen Mikrofoneinstellungen liegt

**Comment by kkaiser12** [comment]
Also bei mir funktioniert es, allerdings nur mit Chrome.
Ich verstehe noch nicht ganz, wie das mit dem Hinzufügen von neuen Fächern funktioniert. Wann ruft man das auf? Gibt es da bei der Begrüßung zwei Optionen, also Fächer hinzufügen oder ausgeben?

**Comment by ngaeng** [comment]
Danke fürs Testen, ich krieg das irgendwie selbst in Chrome nicht auf die Reihe.

Soll man neue Fächer hinzufügen können? Ich dachte wir nehmen nur die die eh im Stundenplan vorkommen, und machen nur die Gegenstände änderbar. Falls ja muss ich das noch bisschen umbauen. 
Ich denk ich hab auch das mit dem Anfang nicht richtig verstanden. Ich dachte es wär vll ein bisschen viel Wiederholung wenn Alexa jedes mal beim Willkommen darauf hinweist, dass man die config ändern kann, deshalb hab ich in help auf das Kommando "Gegenstand hinzufügen" hingewiesen statt das jedes mal zu sagen. Kann aber sein, dass es dadurch für den User zu unklar ist, wie er das machen kann. Das sollte man aber auch ändern können, die Frage ist halt für was das help dann da ist.

**Comment by Chrysotomus** [comment]
Also ich denke, dass es durchaus Sinn macht, nicht in dem "Willkommen"-Block darauf hingewiesen zu werden, dass man Gegenstände hinzufügen kann. Sonst wäre das Hilfe-Kommando ja auch hinfällig. Ich denke es ist also ganz gut, wenn Alexa einen beim Begrüßen nicht darauf hinweist, dass man die Gegenstände wechseln kann. Was man machen könnte, auch wenn ich das für recht überflüssig (oder gar nervig) halte:
Alexa könnte bei der Begrüßung noch daran erinnern: "Wenn du dich nicht an alle Funktionen erinnern kannst, kannst du mich jederzeit um 'Hilfe' bitten".

Edit: Ich würde vorschlagen, dass Alexa bei der Begrüßung nur daran erinnert, dass man eine neue Fach-Gegenstandszuordnung machen kann, wenn die Gegenstandsliste aktuell leer ist.
