### ISSUE TITLE
Stopp

### ISSUE THREAD

**Issue by sfrank13** [sweIhm-ws2018-19/skillproject-fr-14#24]

**Comment by sfrank13** [comment]
Name | Stopp (UC 7)
-- | --
Kurzbeschreibung | Der User soll jederzeit die 			Möglichkeit haben das Programm zu stoppen bzw. zu pausieren.
Akteure | User
Auslöser | User sagt zu Alexa: „Stopp“
Vorbedingungen | keine
Eingehende Informationen | keine
Ergebnis(se) | Das Programm hält an der Stelle 			des „Stopp“ Aufrufs an. Jedoch weiß das Programm wie es 			fortfahren soll.
Nachbedingungen | keine
Ablauf | **1. Programm anhalten:** 	<br>		User sagt zu Alexa „Stopp“, 			somit hält das Programm an dieser Stelle an. Dies ist 			beispielsweise nützlich, wenn Alexa dem User sagt, was dieser in 			seine Tasche packen soll. Denn der Anwender will meistens gleich 			die Sachen suchen und in seine Tasche packen, damit man sich nicht 			so viele Dinge auf einmal merken muss.  	<br>		 			**2. Programm weiter ausführen:** 		<br>	Um das Programm weiter laufen zu 			lassen muss der User nur zu Alexa sagen: „Weiter“. Somit wird 			der Skill an der Stelle fortgesetzt wo er angehalten wurde.
Offene Punkte | keine
Änderungshistorie | geändert am 12.11.2018 von Sara 			Frank
Sonstiges, Anmerkungen | keine

**Comment by sfrank13** [comment]
Das ist der Issue für den Stopp Befehl. Ich denke, dass es so passen sollte, aber für Änderungsvorschläge bin ich offen.

**Comment by kkaiser12** [comment]
**User Story: Stopp**
Als Nutzer möchte ich die Aufzählung der Gegenstände kurz unterbrechen können, um z.B. etwas zu suchen, was ich einpacken muss. Danach soll die Aufzählung fortgesetzt werden können. 

**Akzeptanzkriterien**
Stelle an der die Aufzählung unterbrochen wurde, wird gespeichert.

**Comment by sfrank13** [comment]
Name | Stopp (UC 7)
-- | --
Kurzbeschreibung | Der User soll jederzeit die 			Möglichkeit haben das Programm zu stoppen bzw. zu pausieren.
Akteure | User
Auslöser | User sagt zu Alexa: „Stopp“
Vorbedingungen | keine
Eingehende Informationen | keine
Ergebnis(se) | Das Programm hält an der Stelle 			des „Stopp“ Aufrufs an. Jedoch weiß das Programm wie es 			fortfahren soll.
Nachbedingungen | keine
Ablauf | 1. Programm anhalten<br> 			User sagt zu Alexa „Stopp“, 			somit hält das Programm an dieser Stelle an. Dies ist 			beispielsweise nützlich, wenn Alexa dem User sagt, was dieser in 			seine Tasche packen soll. Denn der Anwender will meistens gleich 			die Sachen suchen und in seine Tasche packen, damit man sich nicht 			so viele Dinge auf einmal merken muss.  			 		<br> 	2. Programm weiter ausführen<br>  			Um das Programm weiter laufen zu 			lassen muss der User nur zu Alexa sagen: „Weiter“. Somit wird 			der Skill an der Stelle fortgesetzt wo es angehalten wurde.
Offene Punkte | keine
Änderungshistorie | geändert am 12.11.2018 von Sara 			Frank
Sonstiges, Anmerkungen | keine

**Comment by kkaiser12** [comment]
Hey Leute,
 ich habe ja den Stop-Skill für diesen Sprint. Ich habe jetzt festgestellt, dass es, wenn wir das Ganze so umsetzen, wie es in der User Story steht ziemlich kompliziert ist und wahrscheinlich mindestens so aufwendig wie unsere Hauptfunktionen. Man kann Alexa nämlich nicht länger als ein paar Sekunden anhalten, weil sie sonst aus dem Skill springt. Eine andere Gruppe, die ein ähnliches Problem hatte, hatte die Idee, in der Zwischenzeit eine leere Musikdatei abzuspielen. Danach muss man dann irgendwie wieder an die richtige Stelle von vorher springen. Es wäre schon machbar, ich wäre da aber jetzt echt erstmal beschäftigt und komme wahrscheinlich auch nicht mehr groß dazu, mich um was anderes zu kümmern. 
Was meint ihr? Sollen wir das Ganze trotzdem machen oder sollen wir es auf die Idee abändern, die wir ursprünglich hatten, dass mit "Stop" einfach nur der Skill gestoppt wird?

**Comment by Chrysotomus** [comment]
Wenn das tatsächlich so viel Aufwand ist, sollten wir auf diese 'Pause' Funktion vermutlich verzichten. Ich denke ein 'Stopp' Intent, der das ganze Programm beendet ist absolut ausreichend. Wenn der User nicht mit der Geschwindigkeit klarkommt, in der Alexa die Sachen vorliest, wird er wohl oder übel nochmal nachfragen müssen. Wir haben schließlich auch noch andere Fächer in der wir Abgaben erledigen zu erledigen haben. Dann kommt dieses Projekt halt minimal kürzer. Was denkt der Rest des Teams?

PS: Falls wir die 'Pause' Funktion doch umsetzen klingt die leere Sounddatei nach einer guten Idee.

**Comment by sfrank13** [comment]
Ich denke auch, dass es völlig ausreichend ist, wenn wir mit der "Stop" Funktion einfach nur bewirken, dass das Programm beendet wird. Mir war nämlich auch nicht bewusst, dass man Alexa nicht länger als paar Sekunden anhalten kann...
Falls wir irgendwann noch einmal ewig Zeit haben, kann man sich das mit der Musik nochmals überlegen, aber bis jetzt würde ich das rauslassen.

**Comment by kkaiser12** [comment]
Also ich selbst würde auch sagen, wir haben mit den anderen Sachen schon genug zu tun. Im dritten Sprint kommen schließlich auch noch die Wetterdaten dazu.
