### ISSUE TITLE
Probleme mit Workspace.xml

### ISSUE THREAD

**Issue by Chrysotomus** [sweIhm-ws2018-19/skillproject-fr-14#26]
Ich habe Probleme damit, meine Dateien auf Github zu pushen. Nachdem ich geaddet und commited habe, habe ich Probleme mit dem Workspace.xml file in der .idea. Es ist mir nicht mehr möglich etwas auf GitHub zu pushen. Ich habe leider elegante Lösung gefunden und würde vorschlagen, dass wir uns mal treffen und uns das Problem zusammen ansehen, da ja scheinbar mehrere dieses Problem haben.. Ich habe sicherheitshalber die Kommandozeilenantwort unten eingefügt, als ich mein Projekt pushen auf Github pushen wollte.
```
From https://github.com/sweIhm-ws2018-19/skillproject-fr-14
 * branch            develop    -> FETCH_HEAD
Auto-merging tasche_packen/.idea/workspace.xml
CONFLICT (content): Merge conflict in tasche_packen/.idea/workspace.xml
Automatic merge failed; fix conflicts and then commit the result. 
```

**Comment by ngaeng** [comment]
Workspace.xml ist jetzt in gitignore, d.h. alles sollte konfliktfrei laufen.
