### ISSUE TITLE
Sonarqube

### ISSUE THREAD

**Issue by ngaeng** [sweIhm-ws2018-19/skillproject-fr-14#27]
Derzeit bekommen wir bei travis-CI beim Build immer folgenden Fehler:
> Project was never analyzed. A regular analysis is required before a branch analysis

Ich habe jetzt erstmal das yml-File zurückgesetzt, der Build in travis funktioniert auch. Ich könnte mir vorstellen, dass das Problem daran hängt, dass wir noch alles im develop-Branch haben. Ich würde vorschlagen, dass wir das erstmal so lassen und erst nächste Woche alles mit dem master-Branch mergen. Falls einem von Euch eine Möglichkeit einfällt das anderweitig zu fixen können wir das natürlich sofort machen.

**Comment by Chrysotomus** [comment]
Alles klar, vielen Dank für das Update. Leider fällt mir akutell auch keine Lösung zu diesem Problem ein. Vielleicht sollten wir deswegen nochmal die Frau Socher ansprechen, in dem Fall, dass wir das Problem selber nicht beheben können.

**Comment by ngaeng** [comment]
[Link zu unserem Sonarcloud Projekt](https://sonarcloud.io/dashboard?id=alexa-skills-kit-samples%3Apack_bag)
Ist gefixed, wir mussten das nur mit dem master branch mergen.
Probleme bleiben noch:
* das E-Rating bei Vulnerabilities, da können wir aber wenig machen, solange wir das Passwort noch über ein textfile übergeben
* die Bugs
* die Test-Coverage (muss man die Tests irgendwo beim Maven build besonders spezifizieren, damit die da auftauchen oder warum fallen die bei uns nicht ins Gewicht?)

Wär gut wenn wir zumindest die Bugs noch auf A kriegen. Falls wir das mit dem ZPA im 1. Sprint nicht hinbekommen würde ich das File vll wieder rausnehmen, damit wir da zumindest diesesmal ein A-Rating haben

**Comment by sfrank13** [comment]
Alles klar, danke für das Update!

**Comment by ngaeng** [comment]
Die Tests sind jetzt im richtigen Ordner. Falls jemand von Euch noch neue Tests machen will (wir haben bisher nur eine coverage von 17% aber ohne die Handler zu covern geht wenn dann nur noch was bei den Klassen von @Chrysotomus ) bitte nicht einfach pushen, sondern erst pullen und in die neue Ordnerstruktur integrieren. Außerdem musste dafür die Zeile

> \<sourceDirectory>src\</sourceDirectory> 

aus dem pom.xml auskommentiert werden, also bitte nicht einfach euers  drübermergen, sonst geht unser build nicht mehr.

Falls wir das Passwort-file dieses Mal nicht brauchen löscht das bitte, das ist so ziemlich alleinverantwortlich für das E in Vulnerabilities

**Comment by ngaeng** [comment]
Okay passt soweit, travis builded und in Sonarqube haben wir zwar noch ein C bei bugs, aber sollte soweit für den 1.Sprint reichen hoffe ich

**Comment by ngaeng** [comment]
Okay vorausgesetzt keiner ändert mehr was am Code sieht das alles wunderbar aus auf Sonarcloud
