### ISSUE TITLE
Jedes mal, wenn ich Geld abhebe verliere 50 Cent?

### ISSUE THREAD

**Issue by tobikuch** [sweIhm-ws2018-19/skillproject-fr-14#3]
Warum ist der Geldbetrag in int?

**Comment by Heusini** [comment]
I had the problem too. 
maybe fix this: `private  int betrag;` 
Schiedermeier would not be proud of the german variable names.
There's also a nice feature with git clone push commit add(and many more).
You dont need funny zip files.
