### ISSUE TITLE
ZPA-Stundenplanabfrage

### ISSUE THREAD

**Issue by Chrysotomus** [sweIhm-ws2018-19/skillproject-fr-14#30]
Name | ZPA-Stundenplan-Abfrage
-- | --
Kurzbeschreibung | Der Funktion soll automatisch 			das ZPA-System nach dem Wochenplan fragen, um die heutigen 			Vorlesungen und Praktika herauszufinden.
Akteure | User
Auslöser | Der User möchte erinnert 			werden, was er heute einpacken soll.
Vorbedingungen | ZPA-Accountdaten müssen in 			einer Datenbank hinterlegt sein
Eingehende 			Informationen | ZPA-Accountdaten
Ergebnis(se) | Vorlesungen und Praktika die an 			diesem Tag tatsächlich stattfinden, werden ausgegeben
Nachbedingungen | Der User wird aus dem ZPA wieder 			ausgeloggt
Ablauf | 1. Der User möchte wissen 			was er einpacken soll 			Wenn der User fragt, was er 			heute einpacken soll, wird das ZPA-System nach dem Wochenplan 			gefragt. Nach erfolgreichem Login gibt das ZPA-System den 			Wochenplan zurück. Aus diesem werden dann die Vorlesungen und 			Praktika des heutigen Tages gefiltert und zurückgegeben
Offene Punkte | ----
Änderungshistorie | Erstellt am 30.11.2018
Sonstiges, 			Anmerkungen | ----

User Story: ZPA-Stundenplan-Abfrage
Als User möchte ich, dass mein Stundenplan automatisch aus dem ZPA abgefragt wird, damit ich nur an die wirklich gebrauchten Unterlagen erinnert werde.

Akzeptanzkriterien
Wenn die ZPA-Server online sind, soll die Liste der heutigen Vorlesungen und Praktika ausgegeben werden.

**Comment by Chrysotomus** [comment]
Hier ist die User Story zur ZPA-Stundenplan-Abfrage. Ich würde euch bitten, das hier einmal Korrektur zu lesen und mit Vorschlägen zu kommen, was wir tun sollen, wenn das ZPA nicht erreichbar ist, oder keine Accountdaten eingetragen wurden. Ich bin mir auch nicht allzusicher, ob bei der Zeile 'Eingehende Informationen' in der oberen Tabelle ZPA-Accountdaten stehen sollte. 
Außerdem muss ich noch ein Fachklassenmodell dafür erstellen, oder missverstehe ich etwas?

**Comment by kkaiser12** [comment]
Also ich weiß ehrlich gesagt nicht, ob wir diese Sonderfälle berücksichtigen müssen. Alexa könnte ja eine entsprechende Fehlermeldung ausgeben, aber ich finde, dass das eher niedrigere Priorität hat und noch gemacht werden könnte, wenn am Ende noch Zeit bleibt. 
Das mit den Accountdaten finde ich schon sinnvoll, da der Stundenplan ja abhängig vom Account ausgegeben wird.

**Comment by ngaeng** [comment]
Ich hab deinen Issue mal in den Product Backlog, weil der da nicht drin war. Bitte verschiebe es wenn du fertig bist in "Done", damit ich weiß, dass ich meinen Code anpassen kann falls noch genug Zeit ist

**Comment by Chrysotomus** [comment]
Passt, vielen Dank. Das Programm ist fertig geschrieben und voll funktionstüchtig. Die Ausgaben sind auch so, wie du sie dir gewünscht hast. Ich werde morgen noch die User Story und die Anwendungsfallbeschreibung finalisieren.
Edit: Das Programm ist auch schon gepushed. Du kannst es also schon testen
