### ISSUE TITLE
Gegenstände für den Skill

### ISSUE THREAD

**Issue by sfrank13** [sweIhm-ws2018-19/skillproject-fr-14#33]
Hier eine kleine Liste von Gegenständen die man zu jedem Fach brachen könnte.

Operation Research
- Skript
- Block
- Kugelschreiber
- Bleistift
- bunte Stifte
- Geodreieck
- Taschenrechner

Differentialrechnung in Rn und Differentialgleichungen
- Block
- Taschenrechner
- Kugelschreiber
- Bleistift

Numerische Mathematik
- Laptop
- Maus
- Stifte
- Block

Software Engineering
- Laptop
- Maus
- Block
- Stifte
- Diagramm-Tafel
- evtl. Alexa

Netzwerke
- Laptop 
- Maus
- Ladekabel
- Block
- Stifte

Wahrscheinlichkeitsrechnung und Statisik
- Block
- bunte Stifte
- Kugelschreiber

Datenbanksysteme
- Block 
- bunte Stifte
- Laptop
- Kugelschreiber

Algorithmen und Datenstrukturen
- Laptop
- Block
- Kugelschreiber
- Ladekabel

**Comment by ngaeng** [comment]
Okay vielen Dank! Das können wir so eintragen

**Comment by ngaeng** [comment]
@kkaiser12 @Chrysotomus 
Ich werde das mal so als default-Werte in die Datenbank eintragen. Der Code dafür wird in kürze gepushed, dh wenn ihr den pulled müsstet ihr beim Developer die neuen Slot-Werte hinzufügen wenn ihr testet.
"bunte Stifte" müssen wir mit der ID "Buntstifte" eintragen, weil zwei Wörter nicht funktionieren.

**Comment by Chrysotomus** [comment]
@ngaeng Alles klar, danke für den Hinweis nochmal
