### ISSUE TITLE
Übungsblatt 2 - Aufgabe 3

### ISSUE THREAD

**Issue by ngaeng** [sweIhm-ws2018-19/skillproject-fr-14#5]
Falls der Reviewer dieser Aufgabe weiß wie man den Block oben links in der Ecke (mit dem Systemnamen) besser beschriftet (nicht nur mit dem Textoverlay) wär das glaub ich ganz gut

**Comment by ngaeng** [comment]
![aufgabe3](https://user-images.githubusercontent.com/43876351/47558161-ca366000-d912-11e8-943c-6b96d413f8dd.jpg)

**Comment by Chrysotomus** [comment]
Sieht soweit gut aus. Die Akteure sollten nur noch in den Block rein und die Überschrift könnte ergänzt werden zu "Nutzungsfall: Mitfahrgelegenheitsvermittlung".

**Comment by ngaeng** [comment]
Ich denke nicht, dass die Akteure in den Block sollen. In der Aufgabenstellung ist ja ein template gegeben
