### ISSUE TITLE
Übungsblatt 2: Aufgabe 1

### ISSUE THREAD

**Issue by sfrank13** [sweIhm-ws2018-19/skillproject-fr-14#6]
Bitte einmal überprüfen ob es möglich ist bzw. richtig ist, wenn man bei dem "Blitz einstellen"  die Funktionen "ein,aus,auto" so an gibt. Denn das Blitz einstellen enthält ja diese Funktionen.

**Comment by sfrank13** [comment]
![aufgabe1](https://user-images.githubusercontent.com/43876401/47558334-26997f80-d913-11e8-9f10-d8b84f12d00b.png)

**Comment by Chrysotomus** [comment]
Die Pfeile vom Akteur aus sollten einfache Linien sein - Dort gehören keine Pfeilspitzen hin. 
Ich würde das Strichmännchen noch mit in die Box packen und die Überschrift "Nutzungsfall: Kamera-App" nennen. (Nutzungsfall klingt meiner Meinung nach zwar nicht schön, aber das wäre nach Österreichs Buch wohl die naheliegendste Übersetzung). Bezüglich der gestrichelten Linien, bin ich ich mir tatsächlich nicht sicher. Ich würde das gerne nochmal mit dem gesamten Team durchsprechen, da ich selber auch keine weiteren Informationen finde

**Comment by Chrysotomus** [comment]
Okay, das mit den gestrichelten Linien hat sich geklärt - das passt so (Pfeilspitzen müssen allerdings weg). Ich bin mir nur nicht über die Beschriftung sicher. Außerdem ist mir noch aufgefallen, dass die Überschrift in einem eingenen kleinen Block mit abgeschnittener Ecke in der oberen linken Ecke des großen Blocks sein sollte. Ich bitte um Rückmeldung, falls ich mich unverständlich ausgedrückt habe.

**Comment by sfrank13** [comment]
![aufgabe1](https://user-images.githubusercontent.com/43876401/47785429-07329600-dd09-11e8-80c4-60c836e4d582.png)

**Comment by Chrysotomus** [comment]
Sieht gut aus. Ich würde sagen, dass du das so hochladen und im Wiki verlinken kannst. (Bezüglich der letzten Vorlesung, glaube ich, dass das "Nutzungsfall: " im Titel doch nicht nötig gewesen wäre. Ich glaube aber kaum, dass das einer Korrektur bedarf)
