### ISSUE TITLE
Übungsblatt 2: Aufgabe 6

### ISSUE THREAD

**Issue by kkaiser12** [sweIhm-ws2018-19/skillproject-fr-14#8]

**Comment by kkaiser12** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-14/tree/master/UML/Uebungsblatt2/Aufgabe_6

**Comment by ngaeng** [comment]
Sieht sehr gut aus, va auch echt gut strukturiert, da gibts nichts zu verbessern denke ich

**Comment by kkaiser12** [comment]
Hier nochmal als Bild: 

![](https://github.com/sweIhm-ws2018-19/skillproject-fr-14/raw/master/UML/Uebungsblatt2/Aufgabe_6/uebung_2_aufgabe_6.png)
