### ISSUE TITLE
Übungsblatt 2: Aufgabe 8

### ISSUE THREAD

**Issue by kkaiser12** [sweIhm-ws2018-19/skillproject-fr-14#9]

**Comment by kkaiser12** [comment]
https://github.com/sweIhm-ws2018-19/skillproject-fr-14/tree/master/UML/Uebungsblatt2/Aufgabe_8

**Comment by ngaeng** [comment]
Sieht gut aus

**Comment by kkaiser12** [comment]
Hier nochmal als Bild: 

![uebung_2_aufgabe_8](https://user-images.githubusercontent.com/43876345/47804964-6f4ba100-dd36-11e8-8728-7da266845b8f.png)
